spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dk_security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Deepak@333
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      format_sql: true
